name: Node.js CI and Docker Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Build Docker image
      run: |
        docker build -t my-apache-image .
    
    - name: Run Docker container
      run: |
        docker run -d -p 80:80 my-apache-image

    # Sleep for 15 seconds
    - name: Sleep for 15 seconds
      run: |
        echo "Sleeping for 15 seconds"
        sleep 15
